In [2]:
import numpy as np

original_list = [12.23, 13.32, 100, 36.32]
array_1d = np.array(original_list)
print("1D NumPy array:", array_1d)


1D NumPy array: [ 12.23  13.32 100.    36.32]


In [3]:
import numpy as np

matrix_3x3 = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix from 2 to 10:\n", matrix_3x3)


3x3 Matrix from 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
import numpy as np

null_vector = np.zeros(10)
print("Null vector:", null_vector)

null_vector[6] = 11
print("After updating 6th value to 11:", null_vector)


Null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After updating 6th value to 11: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:
import numpy as np

array_12_to_38 = np.arange(12, 38)
print("Array from 12 to 38:\n", array_12_to_38)


Array from 12 to 38:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [6]:
import numpy as np

int_array = np.array([1, 2, 3, 4])
float_array = int_array.astype(float)

print("Original array:", int_array)
print("Converted to float:", float_array)


Original array: [1 2 3 4]
Converted to float: [1. 2. 3. 4.]


In [7]:
import numpy as np

centigrade = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])
fahrenheit = centigrade * 9/5 + 32

print("Centigrade:", centigrade)
print("Fahrenheit:", fahrenheit)


Centigrade: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Fahrenheit: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [8]:
import numpy as np

original_array = np.array([10, 20, 30])
appended_array = np.append(original_array, [40, 50, 60, 70, 80, 90])

print("Original array:", original_array)
print("After append:", appended_array)


Original array: [10 20 30]
After append: [10 20 30 40 50 60 70 80 90]


In [12]:
import numpy as np

random_array = np.random.rand(10)

print("Array:", random_array)
print("Mean:", np.mean(random_array))
print("Median:", np.median(random_array))
print("Standard Deviation:", np.std(random_array))


Array: [0.86290336 0.90332851 0.6122205  0.77654144 0.10757125 0.15073648
 0.50504592 0.03906173 0.00937421 0.85661888]
Mean: 0.4823402267097189
Median: 0.5586332084036362
Standard Deviation: 0.351665784517997


In [13]:
import numpy as np

array_10x10 = np.random.rand(10, 10)

print("10x10 Array:\n", array_10x10)
print("Min:", np.min(array_10x10))
print("Max:", np.max(array_10x10))


10x10 Array:
 [[0.51297311 0.57848908 0.08350826 0.8583869  0.06137579 0.80028437
  0.03289744 0.94292463 0.45713346 0.78154115]
 [0.92346454 0.35494723 0.88274074 0.48328786 0.89238809 0.34201582
  0.28638282 0.22934925 0.23792633 0.48572   ]
 [0.64145128 0.49071219 0.40102643 0.43496709 0.52049082 0.3942382
  0.88457756 0.27153127 0.66342999 0.48532819]
 [0.71383218 0.23173663 0.98815526 0.27305702 0.05029885 0.7277122
  0.77894342 0.37122098 0.39256449 0.18398602]
 [0.52909158 0.56674559 0.16101204 0.61819711 0.66466672 0.6072975
  0.52333317 0.50767842 0.46622313 0.59600636]
 [0.00482549 0.03626015 0.9950719  0.36132094 0.13382187 0.15053095
  0.68011517 0.81157623 0.95449432 0.2563904 ]
 [0.3516726  0.68649983 0.59455002 0.81027216 0.77590365 0.89714369
  0.69199437 0.09760127 0.12855084 0.60514566]
 [0.20132986 0.42853558 0.43103227 0.57216113 0.75241474 0.4465462
  0.0458793  0.95990994 0.38031391 0.73325478]
 [0.66636754 0.06641572 0.94598547 0.67888063 0.20090545 0.03214858
  

In [14]:
import numpy as np

array_3x3x3 = np.random.rand(3, 3, 3)
print("3x3x3 Random Array:\n", array_3x3x3)


3x3x3 Random Array:
 [[[0.44716352 0.3041506  0.66411591]
  [0.07854115 0.49213553 0.86179072]
  [0.02379904 0.04179105 0.7651259 ]]

 [[0.17939656 0.3241788  0.51703362]
  [0.95140295 0.66691394 0.00311966]
  [0.77685182 0.93821524 0.15588814]]

 [[0.06808513 0.65406172 0.65825948]
  [0.69252414 0.00910051 0.61384614]
  [0.80452842 0.732905   0.51506559]]]
